/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    serverComponentsExternalPackages: ['mongoose']
  },
  api: {
    bodyParser: {
      sizeLimit: '50mb', // Increased from 10mb for larger file uploads
    },
    responseLimit: '50mb',
  },
  // Optimize for faster builds and responses
  compress: true,
  poweredByHeader: false,
  env: {
    MONGODB_URI: process.env.MONGODB_URI,
    GOOGLE_DRIVE_CLIENT_ID: process.env.GOOGLE_DRIVE_CLIENT_ID,
    GOOGLE_DRIVE_CLIENT_SECRET: process.env.GOOGLE_DRIVE_CLIENT_SECRET,
    GOOGLE_DRIVE_REDIRECT_URI: process.env.GOOGLE_DRIVE_REDIRECT_URI,
    GOOGLE_DRIVE_REFRESH_TOKEN: process.env.GOOGLE_DRIVE_REFRESH_TOKEN,
    GOOGLE_DRIVE_DEFAULT_FOLDER_ID: process.env.GOOGLE_DRIVE_DEFAULT_FOLDER_ID,
    GOOGLE_DRIVE_MONTHLY_REPORT_FOLDER_ID: process.env.GOOGLE_DRIVE_MONTHLY_REPORT_FOLDER_ID,
    GOOGLE_DRIVE_FINANCIAL_STATEMENT_FOLDER_ID: process.env.GOOGLE_DRIVE_FINANCIAL_STATEMENT_FOLDER_ID,
    GOOGLE_DRIVE_EVENT_PROPOSAL_FOLDER_ID: process.env.GOOGLE_DRIVE_EVENT_PROPOSAL_FOLDER_ID,
    GOOGLE_DRIVE_MINISTRY_UPDATE_FOLDER_ID: process.env.GOOGLE_DRIVE_MINISTRY_UPDATE_FOLDER_ID,
    GOOGLE_DRIVE_BUILDING_PROPERTY_DOCUMENTS_FOLDER_ID: process.env.GOOGLE_DRIVE_BUILDING_PROPERTY_DOCUMENTS_FOLDER_ID,
    GOOGLE_DRIVE_MEMBERSHIP_RECORDS_FOLDER_ID: process.env.GOOGLE_DRIVE_MEMBERSHIP_RECORDS_FOLDER_ID,
    GOOGLE_DRIVE_PASTORAL_CREDENTIALS_FOLDER_ID: process.env.GOOGLE_DRIVE_PASTORAL_CREDENTIALS_FOLDER_ID,
    GOOGLE_DRIVE_OTHER_DOCUMENTS_FOLDER_ID: process.env.GOOGLE_DRIVE_OTHER_DOCUMENTS_FOLDER_ID,
  }
};

export default nextConfig;
